### ISSUE TITLE
memory allocation error with 0.8.1

### ISSUE THREAD

**Issue by mojjj** [Anarchid/zkgbai#11]
might be unrelated, but 3 humans vs 2 circuit + 2 zkgb => window freeze when com plopp should be, infolog attached.

http://pastebin.com/afNXHbgn

**Comment by aeonios** [comment]
That error log doesn't suggest anything went wrong with kgb. If kgb has a memory allocation error then java throws an OOM exception, but that was all C++ and looked like spring itself had some sort of error. It could possibly be related to circuit but I don't really know.

**Comment by mojjj** [comment]
well now, when i only use one zkgb as oponent, the result is the same. does not happen with CAI or circuit (nor any multiplayer)...

http://i.imgur.com/NkUVL7g.png

tell me what to do to get more intel to fix this issue if you have an idea...

**Comment by DeinFreund** [comment]
Do you have the same problem with all JavaAIs? Try for example http://zero-k.info/Forum/Thread/22533

Have you tried monitoring memory usage with something like htop?

**Comment by aeonios** [comment]
The only thing notable I could see is that you're running linux. It seems to be using the correct jvm though, so at least that shouldn't be a problem. As DF said, either test CSI or the java nullOOAI and see if that gives the same result. There's not enough info to tell if it's a spring issue or if it's your system or what.

**Comment by mojjj** [comment]
i have 16g memory i doubt that is an issue there...
infologs, using 0.8.2 of zkgb
CSI 1337 crashes the same way => : http://pastebin.com/A8PzWRaZ
NullOOJavaAI", Version:"0.1 too => http://pastebin.com/aLtHsyEt

**Comment by Anarchid** [comment]
This looks like an engine issue, then. I can replicate this, so maybe i'll find some clues.

**Comment by Anarchid** [comment]
@mojjj i have succeeded in launching zkgbai (also nullai and csi) by passing Spring a proper JAVA_HOME environment variable.  

It seems that Spring fails at detecting JRE on newer Ubuntu.

This is an engine bug.

**Comment by mojjj** [comment]
nice.
is this limited to ubuntu or other lunix-systems too? why not windows? do you report this to engine tracker? 

could you share how to pass the env var?

**Comment by Anarchid** [comment]
`JAVA_HOME=/usr/share/whatever/ ~/.spring/engine/103.0.1-abracadabra/spring ~/somewhere/startscript.spring`

You can also `export`, of course.

The method i used to find the current java home was either `update-alternatives --config java` or `which java`, can't be sure. Also i removed last two path elements (`/bin/java`) to get to proper JAVA_HOME and not just binary location.

I have not reported it on mantis yet.

**Comment by mojjj** [comment]
i reported it on mantis
https://springrts.com/mantis/view.php?id=5354
