### ISSUE TITLE
ZKGBAI freezes on start on Spring 103.0.1-516

### ISSUE THREAD

**Issue by Anarchid** [Anarchid/zkgbai#14]
After spawning, saying glhf, analyzing the map, parsing the json metalmap message, and merging all its commanders, the AI attempts no further actions. There are no exceptions in infolog. I didnt check `kgbdebug`. This is an engine compatibility and not a game compatibility issue, because same game version on older engine works. 

Circuit doesn't seem to have this problem so it's likely some kind of a logical change.

**Comment by aeonios** [comment]
kgbdebug wouldn't tell you anything useful anyway. :P Not throwing exceptions is a problem though. I'll have to check it out later.

**Comment by ndrchvzz** [comment]
I believe this bug no longer occurs with recent commits of spring.

**Comment by Anarchid** [comment]
Closed until/unless resurfaces. Thanks!
