### ISSUE TITLE
Accomodate mass internal renames

### ISSUE THREAD

**Issue by Anarchid** [Anarchid/zkgbai#16]
Quite a long time ago, ZK renamed all of its units to something more consistent. This, of course, breaks the ai.

A C# tool was written to mass-replace those: https://pastebin.com/RqnQXjyy

A CSV containing a map of previous names to new ones exists: https://cdn.discordapp.com/attachments/278908415756206080/339723824243408898/internalrename_toconvert2.csv

**Comment by aeonios** [comment]
This needs to be done again, and a new binary released. :(

**Comment by Anarchid** [comment]
I did not test the fix, but the names issue is now dealt with.
