### ISSUE TITLE
Wrong behaviour when losing the commander

### ISSUE THREAD

**Issue by ndrchvzz** [Anarchid/zkgbai#17]
When the commander is destroyed and all storage is lost, the AI starts building a lot of generators. This is probably because it sees that the energy storage has gone to zero. So it will keep overcommitting resources to generators, until it will eventually lose the game.
What it should do instead is build some storage, probably even before the commander is killed.

**Comment by aeonios** [comment]
I've had this fixed for a good minute, but never got around to pushing it because of the unit naming thing. It ought to be fixed whenever the next binary is up.
