### ISSUE TITLE
Graph manager broke horribly

### ISSUE THREAD

**Issue by aeonios** [Anarchid/zkgbai#2]
After I added the new porc algorithm suddenly everything broke horribly. After a thorough investigation I found out that graphmanager started shifting metal spots around randomly, causing mexes to be placed off center and other shenanigans. The only thing I changed in graph manager was to add getMexes() (a one liner), which I wasn't using originally when it started breaking. It doesn't throw errors consistently, but sometimes it shows array out of bounds.

**Comment by Anarchid** [comment]
Fixed in 1eccf307fc192a6020f0774ca16d5023fddd2be0
