### ISSUE TITLE
Even one instance of ZKGBAI produces insane CPU load/lag

### ISSUE THREAD

**Issue by lumiera** [Anarchid/zkgbai#3]
Pretty much what title says. Sometimes it begins to lag at the very start, but always at the end of match.

AI is (10af1d0) built from source by javac 1.7.0_91

JRE is openjdk 7

```
java version "1.7.0_91"                        
OpenJDK Runtime Environment (IcedTea 2.6.2) (7u91-2.6.2-1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

Hardware is 2.3 ghz 8-core i7.

**Comment by aeonios** [comment]
This was fixed (more or less) with the latest changes. If you continue having problems complain some more. :P
